AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  gnest-app

  Sample SAM Template for gnest-app
  
Globals:
  Function:
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        NODE_ENV: !Ref NODE_ENV
        JWT_SECRET: !Ref JWT_SECRET
        SERVER_PORT: !Ref SERVER_PORT
        SERVER_HOSTNAME: !Ref SERVER_HOSTNAME
        DATABASE_URL: !Ref DATABASE_URL
        DEFAULT_USER_NAME: !Ref DEFAULT_USER_NAME
        DEFAULT_USER_EMAIL: !Ref DEFAULT_USER_EMAIL
        DEFAULT_USER_PASSWORD: !Ref DEFAULT_USER_PASSWORD

Resources:
  GnestRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      BinaryMediaTypes:
        - "*~1*"

  GnestLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Gnest-Dependencies
      Description: Gnest layer
      ContentUri: app/node_modules
      CompatibleRuntimes:
        - nodejs20.x
      LicenseInfo: MIT
      RetentionPolicy: Retain

  App:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: lambda.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Layers:
        - !Ref GnestLayer
      MemorySize: 1024
      Timeout: 30
      Events:
        AppCall:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId:
              Ref: GnestRestApi
    Metadata:
      BuildMethod: esbuild

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  AppApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${GnestRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
