AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  gnest-app

  Sample SAM Template for gnest-app
  
Globals:
  Function:
    MemorySize: 256
    Timeout: 3

Resources:
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      BinaryMediaTypes:
        - "*~1*"

  App:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: main.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        AppCall:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: ServerlessRestApi
    Metadata:
      BuildMethod: makefile

Outputs:
  AppApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/api/"
