AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  gnest-app

  Sample SAM Template for gnest-app
  
Globals:
  Function:
    CodeUri: app/
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    MemorySize: 256
    Timeout: 100
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

Resources:
  GnestRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      BinaryMediaTypes:
        - "*~1*"

  App:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Events:
        AppCall:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId:
              Ref: GnestRestApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - lambda.ts

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  AppApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${GnestRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
